# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7deb2e1bc94bcea133fa4c7af3b5fac8a4b6c72ef1fa89723176fa931cc34ffbfadd077e53bc0a7ed77d6ab0c2e1e7a3cb70d87b4840cc26fcbd30b946700ffa

test:
  secret_key_base: aa68dfd9353667553f6d918479fbdc1613aade82d81c460adaf0308e2a551748057bcf354749f629905a35ff4d938b0fbace38980de8cc3098a0197f6cde7456

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
